//! Document tree from the filesystem and AGENTS.md generation (D19, D20, D56).

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use walkdir::WalkDir;

use crate::frontmatter::{self, Frontmatter, Status};

pub const AGENTS_FILE: &str = "AGENTS.md";
pub const CONFIG_DIR: &str = ".kmdn";
const HEADER: &str = "<!-- Generated by kmdn. Do not edit by hand; run `kmdn-cli index`. -->";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Document {
    /// Repo-relative path with forward slashes.
    pub path: String,
    pub title: String,
    pub description: Option<String>,
    pub status: Option<Status>,
    pub order: Option<i64>,
    pub tags: Vec<String>,
    pub owner: Option<String>,
    /// Set when frontmatter failed to parse. Document still listed by filename.
    pub frontmatter_error: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
pub struct KbConfig {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub review: ReviewConfig,
}

/// `.kmdn/config.yaml` `review:` section (04-content-model.md).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ReviewConfig {
    #[serde(default = "default_labels")]
    pub labels: Vec<String>,
    /// Offer to post the condensed agent log as a PR comment at submit (D58).
    #[serde(default = "default_true")]
    pub post_agent_log: bool,
}

fn default_labels() -> Vec<String> {
    vec!["kmdn".to_string()]
}
fn default_true() -> bool {
    true
}

impl Default for ReviewConfig {
    fn default() -> Self {
        Self {
            labels: default_labels(),
            post_agent_log: true,
        }
    }
}

pub fn is_excluded_dir(name: &str) -> bool {
    name.starts_with('.')
        || name == "node_modules"
        || name == "target"
        || name.ends_with(".kmdn-worktrees")
}

pub fn read_config(root: &Path) -> KbConfig {
    std::fs::read_to_string(root.join(CONFIG_DIR).join("config.yaml"))
        .ok()
        .and_then(|s| serde_yaml::from_str(&s).ok())
        .unwrap_or_default()
}

/// First `# Heading` in the body, if any.
pub fn first_h1(body: &str) -> Option<String> {
    body.lines()
        .map(str::trim)
        .find_map(|l| l.strip_prefix("# ").map(|t| t.trim().to_string()))
}

pub fn title_for(path: &str, fm: &Frontmatter, body: &str) -> String {
    fm.title
        .clone()
        .or_else(|| first_h1(body))
        .unwrap_or_else(|| {
            Path::new(path)
                .file_stem()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_default()
        })
}

/// One walk of the tree: documents with their bodies, plus every other file with its size.
/// Checks, the index, and submit all read from this so nothing is scanned twice (review P5).
#[derive(Debug, Default, Clone)]
pub struct Scan {
    pub docs: Vec<Document>,
    /// Body text (after frontmatter) per document, same order as `docs`.
    pub bodies: Vec<String>,
    /// Non-markdown files as (repo-relative path, size in bytes).
    pub files: Vec<(String, u64)>,
}

pub fn scan_full(root: &Path) -> Scan {
    let mut docs: Vec<(Document, String)> = Vec::new();
    let mut files = Vec::new();
    for entry in WalkDir::new(root)
        .min_depth(1)
        .sort_by_file_name()
        .into_iter()
        .filter_entry(|e| {
            !(e.file_type().is_dir() && is_excluded_dir(&e.file_name().to_string_lossy()))
        })
        .flatten()
    {
        if !entry.file_type().is_file() {
            continue;
        }
        let rel: PathBuf = entry
            .path()
            .strip_prefix(root)
            .unwrap_or(entry.path())
            .to_path_buf();
        let rel_str = rel.to_string_lossy().replace('\\', "/");
        if !rel_str.ends_with(".md") || rel_str == AGENTS_FILE {
            if rel_str != AGENTS_FILE {
                files.push((rel_str, entry.metadata().map(|m| m.len()).unwrap_or(0)));
            }
            continue;
        }
        let text = std::fs::read_to_string(entry.path()).unwrap_or_default();
        let (fm, body, err) = match frontmatter::parse(&text) {
            Ok((fm, body)) => (fm, body, None),
            Err(e) => (Frontmatter::default(), text.as_str(), Some(e.to_string())),
        };
        let doc = Document {
            title: title_for(&rel_str, &fm, body),
            description: fm.description.clone(),
            status: fm.status.clone(),
            order: fm.order,
            tags: fm.tags.clone(),
            owner: fm.owner.clone(),
            frontmatter_error: err,
            path: rel_str,
        };
        docs.push((doc, body.to_string()));
    }
    docs.sort_by(|a, b| a.0.path.cmp(&b.0.path));
    let (docs, bodies): (Vec<Document>, Vec<String>) = docs.into_iter().unzip();
    Scan {
        docs,
        bodies,
        files,
    }
}

/// Walks `root` for markdown documents, sorted by path. Skips dot dirs and AGENTS.md.
pub fn scan(root: &Path) -> Vec<Document> {
    scan_full(root).docs
}

/// Deterministic AGENTS.md content.
pub fn render_agents_md(config: &KbConfig, docs: &[Document]) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n\n# ");
    out.push_str(config.name.as_deref().unwrap_or("Knowledge base"));
    out.push_str("\n\n");
    if let Some(d) = &config.description {
        out.push_str(d.trim());
        out.push_str("\n\n");
    }
    out.push_str("## How to read this knowledge base\n\n");
    out.push_str("- Every `*.md` file outside `.kmdn/` is a document. Folders are navigation.\n");
    out.push_str("- Format: GitHub Flavored Markdown plus optional YAML frontmatter (`title`, `description`, `owner`, `tags`, `status`, `order`, `reviewed`).\n");
    out.push_str("- Links are relative paths. Images live in `assets/` next to the document.\n");
    out.push_str("- `status: deprecated` documents are kept for history; prefer published ones.\n");
    out.push_str(
        "- Changes go through a pull request. Do not edit this file; it is regenerated.\n\n",
    );
    out.push_str("## Documents\n\n");
    let mut sorted: Vec<&Document> = docs.iter().collect();
    sorted.sort_by(|a, b| {
        let da = Path::new(&a.path)
            .parent()
            .map(|p| p.to_string_lossy().to_string())
            .unwrap_or_default();
        let db = Path::new(&b.path)
            .parent()
            .map(|p| p.to_string_lossy().to_string())
            .unwrap_or_default();
        da.cmp(&db)
            .then(
                a.order
                    .unwrap_or(i64::MAX)
                    .cmp(&b.order.unwrap_or(i64::MAX)),
            )
            .then(a.title.to_lowercase().cmp(&b.title.to_lowercase()))
    });
    for d in sorted {
        out.push_str("- [");
        out.push_str(&d.title);
        out.push_str("](");
        out.push_str(&d.path);
        out.push(')');
        if let Some(desc) = &d.description {
            out.push_str(": ");
            out.push_str(desc.trim());
        }
        match d.status {
            Some(Status::Deprecated) => out.push_str(" (deprecated)"),
            Some(Status::Draft) => out.push_str(" (draft)"),
            _ => {}
        }
        out.push('\n');
    }
    out
}

pub fn agents_md_is_stale(root: &Path) -> bool {
    agents_md_is_stale_for(root, &scan(root))
}

/// Staleness against documents already scanned.
pub fn agents_md_is_stale_for(root: &Path, docs: &[Document]) -> bool {
    let expected = render_agents_md(&read_config(root), docs);
    std::fs::read_to_string(root.join(AGENTS_FILE))
        .map(|s| s != expected)
        .unwrap_or(true)
}

pub fn write_agents_md(root: &Path) -> std::io::Result<bool> {
    write_agents_md_from(root, &scan(root))
}

/// Regenerates AGENTS.md from documents already scanned. Returns whether the file changed.
pub fn write_agents_md_from(root: &Path, docs: &[Document]) -> std::io::Result<bool> {
    let expected = render_agents_md(&read_config(root), docs);
    let p = root.join(AGENTS_FILE);
    if std::fs::read_to_string(&p)
        .map(|s| s == expected)
        .unwrap_or(false)
    {
        return Ok(false);
    }
    std::fs::write(p, expected)?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn kb() -> tempfile::TempDir {
        let d = tempfile::tempdir().unwrap();
        let r = d.path();
        std::fs::create_dir_all(r.join(".kmdn")).unwrap();
        std::fs::write(
            r.join(".kmdn/config.yaml"),
            "name: Platform KB\ndescription: Internal docs.\n",
        )
        .unwrap();
        std::fs::create_dir_all(r.join("ops")).unwrap();
        std::fs::write(
            r.join("ops/deploy.md"),
            "---\ntitle: Deploy\ndescription: How to ship\norder: 1\n---\n# x\n",
        )
        .unwrap();
        std::fs::write(r.join("ops/rollback.md"), "# Rollback fast\n").unwrap();
        std::fs::write(r.join("ops/old.md"), "---\nstatus: deprecated\n---\n").unwrap();
        std::fs::write(r.join("broken.md"), "---\ntitle: [\n---\n").unwrap();
        std::fs::create_dir_all(r.join(".git")).unwrap();
        std::fs::write(r.join(".git/ignored.md"), "no").unwrap();
        d
    }

    #[test]
    fn scans_and_titles() {
        let d = kb();
        let docs = scan(d.path());
        let paths: Vec<&str> = docs.iter().map(|d| d.path.as_str()).collect();
        assert_eq!(
            paths,
            vec![
                "broken.md",
                "ops/deploy.md",
                "ops/old.md",
                "ops/rollback.md"
            ]
        );
        assert_eq!(docs[1].title, "Deploy");
        assert_eq!(docs[3].title, "Rollback fast");
        assert_eq!(docs[2].title, "old");
        assert!(docs[0].frontmatter_error.is_some());
    }

    #[test]
    fn renders_and_detects_staleness() {
        let d = kb();
        assert!(agents_md_is_stale(d.path()));
        assert!(write_agents_md(d.path()).unwrap());
        assert!(!agents_md_is_stale(d.path()));
        assert!(!write_agents_md(d.path()).unwrap());
        let s = std::fs::read_to_string(d.path().join(AGENTS_FILE)).unwrap();
        assert!(s.starts_with(HEADER));
        assert!(s.contains("# Platform KB"));
        assert!(s.contains("- [Deploy](ops/deploy.md): How to ship\n- [old](ops/old.md) (deprecated)\n- [Rollback fast](ops/rollback.md)\n"));
        assert!(!s.contains("ignored"));
    }
}
