#!/usr/bin/env sh
# Regenerates apps/desktop/src/lib/generated from the Rust types (#20, D51).
# CI runs this and fails when the checked-in bindings drift.
set -eu
cd "$(dirname "$0")/.."
out="$PWD/apps/desktop/src/lib/generated"
rm -rf "$out"
mkdir -p "$out"
export TS_RS_EXPORT_DIR="$out"
# Tauri passes JSON numbers, so 64-bit integers are plain numbers on the JS side.
export TS_RS_LARGE_INT=number
cargo test -q -p kmdn-core --features ts export_bindings
cargo test -q -p kmdn-desktop export_bindings
{
  echo "// Generated by scripts/gen-types.sh from the Rust types. Do not edit."
  for f in "$out"/*.ts; do
    b="$(basename "$f" .ts)"
    [ "$b" = "index" ] && continue
    echo "export type * from \"./$b\";"
  done
} > "$out/index.ts"
echo "wrote $(ls "$out" | wc -l) files to apps/desktop/src/lib/generated"
